import asyncio
import json

import pytest

from app.config import load_settings
from app.schemas import RagAnswer
from policies.evidence import EvidenceGate, _model_assessment, _quote_in_source, _answer_statements
from tests.test_rag_v2 import _chunk


def test_verifier_quote_accepts_pdf_layout_whitespace_only():
    assert _quote_in_source("Lhůta činí 30 dnů.", "§ 1\nLhůta\u00a0činí\n\n30 dnů.\n§ 2")
    assert not _quote_in_source("Lhůta činí 300 dnů.", "Lhůta činí 30 dnů.")
    assert not _quote_in_source("Lhůta činí 30 dnů.", "Lhůta nečiní 30 dnů.")
    assert not _quote_in_source("Lhůtačiní 30 dnů.", "Lhůta činí 30 dnů.")
    assert not _quote_in_source(" ", "Lhůta činí 30 dnů.")


@pytest.mark.parametrize("structured", [False, True])
def test_model_assessment_accepts_quote_across_pdf_blank_lines(structured):
    quote = [{"chunk_id": "a", "quote": SOURCE}] if structured else SOURCE
    chunk = _chunk("a", "doc_a", SOURCE.replace(" ", "\n\n"))
    result = _model_assessment(json.dumps(_payload(quote=quote)), [chunk], answer=SOURCE)
    assert result.status == "supported"


SOURCE = "Lhuta pro vyrizeni zadosti je 30 dnu."


def _payload(claim=SOURCE, *, quote=SOURCE, supported=True):
    return {"claims": [{"claim": claim, "claim_type": "main", "chunk_ids": ["a"],
                        "quoted_support": quote, "supported": supported}]}


def _public_policy_chunk(chunk_id="a", document_id="doc_a", text=SOURCE):
    chunk = _chunk(chunk_id, document_id, text)
    chunk.metadata.update({
        "policy_binding_id": "binding_public_test",
        "policy_hash": "sha256:public-test",
        "policy_summary": {"handlingClass": "PUBLIC", "obligations": []},
    })
    return chunk


@pytest.mark.parametrize("suffix,number,expected", [
    ("[chunk_8f6154265d8b4fe7aa42960876f937b0]", "30", "supported"),
    ("[chunk_8f6154265d8b4fe7aa42960876f937b0]", "300", "unsupported"),
    ("[chunk_999_unknown]", "30", "unsupported"),
])
def test_citation_handle_is_not_a_numeric_claim(suffix, number, expected):
    source_id = "chunk_8f6154265d8b4fe7aa42960876f937b0"
    # A single statement with inline citation, as generated by the composer.
    claim = SOURCE.replace("30", number).rstrip(".") + " " + suffix
    payload = _payload(claim)
    if suffix == f"[{source_id}]":
        payload["claims"][0]["claim"] = claim.replace(suffix, "").strip()
    payload["claims"][0]["chunk_ids"] = [source_id]
    result = _model_assessment(json.dumps(payload), [_chunk(source_id, "doc_a", SOURCE)], answer=claim)
    assert result.status == expected


def test_standalone_authorized_citation_is_not_an_answer_statement():
    chunks = [_chunk("chunk_123", "doc_a", SOURCE)]
    assert _answer_statements(SOURCE + "\n[chunk_123]", chunks) == [SOURCE]
    assert _answer_statements(SOURCE + " [chunk_123]", chunks) == [SOURCE]
    assert _answer_statements(SOURCE + "\n[chunk_999]", chunks) == [SOURCE, "[chunk_999]"]


def test_list_claims_preserve_legal_abbreviations_and_every_sentence():
    first = "- Zákon č. 134/2016 Sb. upravuje zakázky. Dodavatel nesmí diskriminovat."
    second = "- Lhůta činí 30 dnů."
    assert _answer_statements(first + "\n" + second, []) == [first, second]


@pytest.mark.asyncio
@pytest.mark.parametrize("invalid", [False, True])
async def test_verification_usage_is_included_even_when_its_output_is_invalid(invalid):
    from app.llm_client import ChatCompletionResult

    class Verifier:
        async def chat_completion_result(self, **kwargs):
            assert kwargs["max_tokens"] == 8192
            return ChatCompletionResult(
                content="invalid" if invalid else json.dumps(_payload()),
                model="verifier", provider="openai", prompt_tokens=10,
                completion_tokens=5, total_tokens=15, estimated_cost_usd=0.002,
            )

    gate = EvidenceGate(load_settings({"AKL_RAG_EVIDENCE_GATE_MODE": "shadow",
                                       "AKL_RAG_EVIDENCE_VERIFIER_MODEL": "verifier"}), Verifier())
    answer = RagAnswer(query_id="q", answer=SOURCE, confidence="high", citations=[], used_chunks=["a"],
                       llm_usage={"model": "composer", "total_tokens": 30, "estimated_cost_usd": 0.003})
    result = await gate.verify_async(answer, [_public_policy_chunk()])
    assert result.llm_usage["total_tokens"] == 45
    assert result.llm_usage["estimated_cost_usd"] == pytest.approx(0.005)
    assert result.llm_usage["verification"]["model"] == "verifier"
    assert answer.llm_usage["total_tokens"] == 30
    assert ("EVIDENCE_VERIFIER_FALLBACK" in result.warnings) is invalid


@pytest.mark.asyncio
async def test_repair_mode_rewrites_partial_answer_once_and_reverifies_it():
    from app.llm_client import ChatCompletionResult

    wrong = SOURCE.replace("30", "300")
    unsupported = _payload(wrong, quote=None, supported=False)
    unsupported["claims"][0]["chunk_ids"] = []
    responses = [json.dumps(unsupported), SOURCE, json.dumps(_payload())]
    calls = []

    class Verifier:
        async def chat_completion_result(self, **kwargs):
            calls.append(kwargs)
            return ChatCompletionResult(
                content=responses.pop(0), model="verifier", provider="openai",
                prompt_tokens=10, completion_tokens=5, total_tokens=15,
                estimated_cost_usd=0.002,
            )

    gate = EvidenceGate(load_settings({"AKL_RAG_EVIDENCE_GATE_MODE": "repair",
                                       "AKL_RAG_EVIDENCE_VERIFIER_MODEL": "verifier"}), Verifier())
    answer = RagAnswer(
        query_id="q", answer=wrong, confidence="high", citations=[], used_chunks=["a"],
        llm_usage={"model": "composer", "prompt_tokens": 20, "completion_tokens": 10,
                   "total_tokens": 30, "cached_prompt_tokens": 0, "estimated_cost_usd": 0.003},
    )
    result = await gate.verify_async(answer, [_public_policy_chunk()])

    assert [call["metadata"]["purpose"] for call in calls] == [
        "rag_claim_evidence_verification",
        "rag_claim_evidence_repair",
        "rag_claim_evidence_reverification",
    ]
    assert [call["max_tokens"] for call in calls] == [8192, 3072, 8192]
    assert result.answer == SOURCE
    assert result.evidence_status == "supported"
    assert result.verification_model == "verifier"
    assert "EVIDENCE_REPAIR_APPLIED" in result.warnings
    assert result.llm_usage["total_tokens"] == 75
    assert result.llm_usage["estimated_cost_usd"] == pytest.approx(0.009)
    assert [item["stage"] for item in result.llm_usage["evidence_pipeline"]] == [
        "verification", "repair", "verification_after_repair"
    ]


@pytest.mark.asyncio
async def test_repair_mode_fails_closed_when_reverification_is_invalid():
    from app.llm_client import ChatCompletionResult

    wrong = SOURCE.replace("30", "300")
    unsupported = _payload(wrong, quote=None, supported=False)
    unsupported["claims"][0]["chunk_ids"] = []
    responses = [json.dumps(unsupported), SOURCE, "invalid"]

    class Verifier:
        async def chat_completion_result(self, **kwargs):
            return ChatCompletionResult(
                content=responses.pop(0), model="verifier", provider="openai",
            )

    result = await EvidenceGate(
        load_settings({"AKL_RAG_EVIDENCE_GATE_MODE": "repair",
                       "AKL_RAG_EVIDENCE_VERIFIER_MODEL": "verifier"}),
        Verifier(),
    ).verify_async(
        RagAnswer(query_id="q", answer=wrong, confidence="high", citations=[], used_chunks=["a"]),
        [_chunk("a", "doc_a", SOURCE)],
    )
    assert result.confidence == "insufficient_source"
    assert result.citations == []
    assert "EVIDENCE_VERIFIER_UNAVAILABLE" in result.warnings


@pytest.mark.asyncio
async def test_repair_cannot_replace_a_better_partially_supported_answer():
    from app.llm_client import ChatCompletionResult

    second = "Dalsi tvrzeni nema oporu."
    answer_text = SOURCE + "\n" + second
    initial = {
        "claims": [
            _payload()["claims"][0],
            {"claim": second, "claim_type": "supporting", "chunk_ids": [],
             "quoted_support": None, "supported": False},
        ]
    }
    repaired = SOURCE.replace("30", "300")
    after_repair = _payload(repaired, quote=None, supported=False)
    after_repair["claims"][0]["chunk_ids"] = []
    responses = [json.dumps(initial), repaired, json.dumps(after_repair)]

    class Verifier:
        async def chat_completion_result(self, **kwargs):
            return ChatCompletionResult(content=responses.pop(0), model="verifier", provider="mock")

    result = await EvidenceGate(
        load_settings({"AKL_RAG_EVIDENCE_GATE_MODE": "repair",
                       "AKL_RAG_EVIDENCE_VERIFIER_MODEL": "verifier"}),
        Verifier(),
    ).verify_async(
        RagAnswer(query_id="q", answer=answer_text, confidence="high", citations=[], used_chunks=["a"]),
        [_public_policy_chunk()],
    )

    assert result.answer == SOURCE
    assert result.evidence_status == "partial"
    assert "EVIDENCE_REPAIR_REJECTED" in result.warnings
    assert "EVIDENCE_REPAIR_APPLIED" not in result.warnings


@pytest.mark.parametrize("claim", [
    "Lhuta pro vyrizeni zadosti je 300 dnu.",
    "Lhuta pro vyrizeni zadosti neni 30 dnu.",
    "Lhuta pro vyrizeni zadosti je 30 hodin.",
    "30 dnu.",
])
def test_lexical_similarity_cannot_prove_a_statement(claim):
    settings = load_settings({"AKL_RAG_EVIDENCE_GATE_MODE": "enforce"})
    result = EvidenceGate(settings).verify(
        RagAnswer(query_id="q", answer=claim, confidence="high", citations=[], used_chunks=["a"]),
        [_chunk("a", "doc_a", SOURCE)],
    )
    assert result.evidence_status == "unsupported"
    assert result.confidence == "insufficient_source"
    assert result.used_chunks == []


def test_extractive_support_preserves_the_actual_passage():
    settings = load_settings({"AKL_RAG_EVIDENCE_GATE_MODE": "enforce"})
    result = EvidenceGate(settings)._assess(SOURCE, [_chunk("a", "doc_a", "Unrelated sentence. " + SOURCE)])
    assert result.status == "supported"
    assert result.claims[0]["quoted_support"] == SOURCE


def test_word_order_is_not_evidence():
    source = "Zadost schvaluje reditel nikoli gestor."
    claim = "Zadost schvaluje gestor nikoli reditel."
    result = EvidenceGate(load_settings({}))._assess(claim, [_chunk("a", "doc_a", source)])
    assert result.status == "unsupported"


@pytest.mark.parametrize("claim", [SOURCE.replace("30", "300"), SOURCE.replace("30", "-30"),
                                    SOURCE.replace("je 30", "neni 30")])
def test_model_cannot_override_number_or_polarity_invariants(claim):
    result = _model_assessment(json.dumps(_payload(claim)), [_chunk("a", "doc_a", SOURCE)], answer=claim)
    assert result.unsupported_main_claim


@pytest.mark.parametrize("mutation", [
    lambda p: p.update(extra=True),
    lambda p: p["claims"][0].update(extra=True),
    lambda p: p.update(claims=[]),
])
def test_model_contract_is_closed_and_preserves_original_claims(mutation):
    payload = _payload()
    mutation(payload)
    with pytest.raises(ValueError):
        _model_assessment(json.dumps(payload), [_chunk("a", "doc_a", SOURCE)], answer=SOURCE)


@pytest.mark.parametrize("mutation", [
    lambda p: p["claims"][0].update(supported="true"),
    lambda p: p["claims"][0].update(chunk_ids=["unknown"]),
    lambda p: p["claims"][0].update(chunk_ids=["a", "a"]),
    lambda p: p["claims"][0].update(quoted_support=[{"chunk_id": "unknown", "quote": SOURCE}]),
])
def test_invalid_model_evidence_is_normalized_to_unsupported(mutation):
    payload = _payload()
    mutation(payload)
    result = _model_assessment(
        json.dumps(payload),
        [_chunk("a", "doc_a", SOURCE)],
        answer=SOURCE,
    )
    assert result.status == "unsupported"
    assert result.unsupported_main_claim
    assert result.claims[0]["chunk_ids"] == []


def test_model_returned_claim_copy_cannot_replace_the_statement_being_verified():
    payload = _payload(claim=SOURCE.replace("30", "300"))
    payload["claims"][0]["claim_type"] = "supporting"
    result = _model_assessment(
        json.dumps(payload),
        [_chunk("a", "doc_a", SOURCE)],
        answer=SOURCE,
    )
    assert result.status == "supported"
    assert result.claims[0]["claim"] == SOURCE


def test_titles_are_not_factual_proof_and_denial_is_respected():
    chunk = _chunk("a", SOURCE, "Unrelated content.")
    assert _model_assessment(json.dumps(_payload()), [chunk], answer=SOURCE).status == "unsupported"
    chunk.text = SOURCE
    assert _model_assessment(json.dumps(_payload(supported=False)), [chunk], answer=SOURCE).status == "unsupported"
    assert _model_assessment(json.dumps(_payload()), [chunk], answer=SOURCE).status == "supported"


def test_model_can_verify_a_grounded_paraphrase_without_rewriting_the_answer():
    claim = "Zadost je nutne vyridit ve lhute 30 dnu."
    assessment = _model_assessment(json.dumps(_payload(claim)), [_chunk("a", "doc_a", SOURCE)], answer=claim)
    assert assessment.status == "supported"
    assert assessment.claims[0]["claim"] == claim


def test_duplicate_json_decision_is_rejected():
    payload = json.dumps(_payload()).replace('"supported": true', '"supported": false, "supported": true')
    with pytest.raises(ValueError, match="duplicate verifier field"):
        _model_assessment(payload, [_chunk("a", "doc_a", SOURCE)], answer=SOURCE)


def _combined_evidence():
    rule = "Zadost se vyrizuje do 30 dnu."
    exception = "U slozite zadosti se lhuta prodluzuje na 60 dnu."
    claim = "Zadost se vyrizuje do 30 dnu, u slozite zadosti se lhuta prodluzuje na 60 dnu."
    payload = _payload(claim, quote=[{"chunk_id": "a", "quote": rule},
                                     {"chunk_id": "b", "quote": exception}])
    payload["claims"][0]["chunk_ids"] = ["a", "b"]
    return claim, payload, [_chunk("a", "doc_a", rule), _chunk("b", "doc_a", exception)]


def test_model_can_support_rule_and_exception_from_separate_passages():
    claim, payload, chunks = _combined_evidence()
    result = _model_assessment(json.dumps(payload), chunks, answer=claim)
    assert result.status == "supported"
    assert result.claims[0]["chunk_ids"] == ["a", "b"]
    assert isinstance(result.claims[0]["quoted_support"], str)


@pytest.mark.parametrize("mutation", [
    lambda p: p["claims"][0]["quoted_support"].pop(),
    lambda p: p["claims"][0]["quoted_support"][1].update(chunk_id="a"),
    lambda p: p["claims"][0]["quoted_support"][1].update(chunk_id="unknown"),
    lambda p: p["claims"][0]["quoted_support"][1].update(extra=True),
])
def test_multi_passage_support_requires_exact_closed_source_mapping(mutation):
    claim, payload, chunks = _combined_evidence()
    mutation(payload)
    result = _model_assessment(json.dumps(payload), chunks, answer=claim)
    assert result.status == "unsupported"
    assert result.unsupported_main_claim
    assert result.claims[0]["chunk_ids"] == []


def test_combined_quote_cannot_borrow_text_from_another_source_or_forge_numbers():
    claim, payload, chunks = _combined_evidence()
    payload["claims"][0]["quoted_support"][0]["quote"] = chunks[1].text
    assert _model_assessment(json.dumps(payload), chunks, answer=claim).status == "unsupported"
    claim, payload, chunks = _combined_evidence()
    claim = claim.replace("60", "600")
    payload["claims"][0]["claim"] = claim
    assert _model_assessment(json.dumps(payload), chunks, answer=claim).status == "unsupported"


@pytest.mark.asyncio
async def test_invalid_verifier_output_is_fail_closed_without_echoing_content(caplog):
    class Verifier:
        async def chat_completion(self, **kwargs):
            return "private-answer-not-json"

    gate = EvidenceGate(load_settings({"AKL_RAG_EVIDENCE_GATE_MODE": "enforce",
                                       "AKL_RAG_EVIDENCE_VERIFIER_MODEL": "test-verifier"}), Verifier())
    result = await gate.verify_async(
        RagAnswer(query_id="q", answer=SOURCE, confidence="high", citations=[], used_chunks=["a"]),
        [_chunk("a", "doc_a", SOURCE)],
    )
    assert result.confidence == "insufficient_source"
    assert "EVIDENCE_VERIFIER_UNAVAILABLE" in result.warnings
    assert "private-answer-not-json" not in caplog.text
    assert SOURCE not in caplog.text


@pytest.mark.asyncio
async def test_verifier_inherits_source_processing_restrictions():
    from answer_composer.composer import _policy_metadata

    captured = {}
    captured_model = None
    chunk = _chunk("a", "doc_a", SOURCE)
    chunk.metadata.update({
        "policy_binding_id": "binding_test", "policy_hash": "sha256:test",
        "policy_summary": {"handlingClass": "RESTRICTED",
                           "obligations": ["NO_EXTERNAL_AI", "NO_EXPORT", "LOCAL_PROCESSING_ONLY"]},
    })

    class Verifier:
        async def chat_completion(self, **kwargs):
            nonlocal captured_model
            captured.update(kwargs["metadata"])
            captured["max_tokens"] = kwargs["max_tokens"]
            captured["response_schema"] = kwargs["response_schema"]
            captured_model = kwargs["model"]
            return json.dumps(_payload())

    gate = EvidenceGate(load_settings({"AKL_RAG_EVIDENCE_GATE_MODE": "enforce",
                                       "AKL_RAG_EVIDENCE_VERIFIER_MODEL": "test-verifier"}), Verifier())
    result = await gate.verify_async(
        RagAnswer(query_id="q", answer=SOURCE, confidence="high", citations=[], used_chunks=["a"]),
        [chunk],
    )
    assert result.evidence_status == "supported"
    assert all(captured[key] == value for key, value in _policy_metadata([chunk]).items())
    assert captured["handling_class"] == "RESTRICTED"
    assert captured["obligations"] == ["LOCAL_PROCESSING_ONLY", "NO_EXPORT", "NO_EXTERNAL_AI"]
    assert captured_model == gate._settings.chat_model
    assert captured["max_tokens"] == 4096
    schema = captured["response_schema"]
    assert schema["additionalProperties"] is False
    assert schema["properties"]["claims"]["minItems"] == 1
    claim_schema = schema["properties"]["claims"]["items"]
    assert claim_schema["additionalProperties"] is False
    assert claim_schema["properties"]["chunk_ids"]["items"]["enum"] == ["a"]
    assert "EVIDENCE_VERIFIER_LOCAL_POLICY_ROUTE" in result.warnings
    assert captured["content_logged"] is False
    assert SOURCE not in json.dumps(captured)


@pytest.mark.asyncio
async def test_verifier_pipeline_timeout_fails_closed_without_retrying_content():
    calls = 0

    class SlowVerifier:
        async def chat_completion(self, **kwargs):
            nonlocal calls
            calls += 1
            await asyncio.sleep(0.05)
            return json.dumps(_payload())

    gate = EvidenceGate(
        load_settings({
            "AKL_RAG_EVIDENCE_GATE_MODE": "repair",
            "AKL_RAG_EVIDENCE_VERIFIER_MODEL": "test-verifier",
            "AKL_RAG_EVIDENCE_VERIFIER_TIMEOUT_SECONDS": "0.001",
        }),
        SlowVerifier(),
    )
    result = await gate.verify_async(
        RagAnswer(query_id="q", answer=SOURCE, confidence="high", citations=[], used_chunks=["a"]),
        [_public_policy_chunk()],
    )

    assert calls == 1
    assert result.confidence == "insufficient_source"
    assert result.citations == []
    assert "EVIDENCE_VERIFIER_UNAVAILABLE" in result.warnings
