apiVersion: 1

datasources:
  - name: Prometheus
    uid: akl-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    uid: akl-loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  - name: Tempo
    uid: akl-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
